"""Production historical backtest runner for BAY TAHMIN Intelligence Engine.

Historical scoring is isolated from live prediction tracking. Every prediction
is generated by the same strict-boundary production engine used in live routes.
"""
from __future__ import annotations
from typing import Any
import football_intelligence_agent_v6 as engine


def _actual_result(fixture: dict[str, Any]) -> str | None:
    goals = fixture.get("goals") or {}
    home, away = goals.get("home"), goals.get("away")
    if home is None or away is None: return None
    return "1" if int(home) > int(away) else "X" if int(home) == int(away) else "2"


def _actual_goals(fixture: dict[str, Any]) -> str | None:
    goals = fixture.get("goals") or {}
    home, away = goals.get("home"), goals.get("away")
    if home is None or away is None: return None
    return "over_2_5" if int(home) + int(away) > 2 else "under_2_5"


def _actual_btts(fixture: dict[str, Any]) -> str | None:
    goals = fixture.get("goals") or {}
    home, away = goals.get("home"), goals.get("away")
    if home is None or away is None: return None
    return "yes" if int(home) > 0 and int(away) > 0 else "no"


def _actual_htft(fixture: dict[str, Any]) -> str | None:
    goals = fixture.get("goals") or {}
    hh, ha = goals.get("half_home"), goals.get("half_away")
    fh, fa = goals.get("home"), goals.get("away")
    if None in (hh, ha, fh, fa): return None
    ht = "1" if int(hh) > int(ha) else "X" if int(hh) == int(ha) else "2"
    ft = "1" if int(fh) > int(fa) else "X" if int(fh) == int(fa) else "2"
    return f"{ht}/{ft}"


def _score_multiclass(probabilities: dict[str, Any], actual: str, keys: tuple[str, ...]) -> dict[str, float]:
    raw = {k: max(0.0, float(probabilities.get(k, 0.0))) / 100.0 for k in keys}
    total = sum(raw.values()) or 1.0
    p = {k: v / total for k, v in raw.items()}
    predicted = max(p, key=p.get)
    brier = sum((p[k] - (1.0 if k == actual else 0.0)) ** 2 for k in keys)
    return {"correct": 1.0 if predicted == actual else 0.0, "brier": round(brier, 6), "actual_probability": round(p.get(actual, 0.0), 6), "predicted": predicted}


def score_prediction(probabilities: dict[str, float], actual: str) -> dict[str, float]:
    return _score_multiclass(probabilities, actual, ("1", "X", "2"))


def _ft_probabilities(model: dict[str, Any]) -> dict[str, float]:
    """Read the canonical FT probabilities exposed by the consistency layer."""
    probs = model.get("ms_probabilities") or model.get("probabilities") or {}
    return {k: float(probs[k]) for k in ("1", "X", "2") if probs.get(k) is not None}


def _ou_probabilities(model: dict[str, Any]) -> dict[str, float]:
    probs = model.get("ou_2_5") or {}
    return {"over_2_5": float(probs["Üst"]), "under_2_5": float(probs["Alt"])} if probs.get("Üst") is not None and probs.get("Alt") is not None else {}


def _btts_probabilities(model: dict[str, Any]) -> dict[str, float]:
    probs = model.get("btts_probabilities") or {}
    return {"btts_yes": float(probs["Var"]), "btts_no": float(probs["Yok"])} if probs.get("Var") is not None and probs.get("Yok") is not None else {}


async def fetch_historical_fixtures(league_id: int, *, season: str | None = None, start_time: int | None = None, end_time: int | None = None, limit: int = 100) -> list[dict[str, Any]]:
    params: dict[str, Any] = {"status": "finished", "include": "stats", "lang": "en", "per_page": 50}
    if season: params["season"] = season
    else:
        if start_time is not None: params["start_time"] = int(start_time)
        if end_time is not None: params["end_time"] = int(end_time)
    fixtures = await engine.five._get_all(f"leagues/{int(league_id)}/fixtures", params)
    fixtures = [f for f in fixtures if _actual_result(f) is not None]
    fixtures.sort(key=lambda f: f.get("kickoff_ts") or 0)
    return fixtures[:max(1, min(int(limit), 250))]


async def backtest_fixtures(fixtures: list[dict[str, Any]]) -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    skipped = 0
    metrics = {"match_result": [], "goals": [], "btts": [], "htft": []}
    for fixture in fixtures:
        actual = _actual_result(fixture)
        if actual is None:
            skipped += 1
            continue
        try:
            row = engine.five._fixture_row(fixture)
            # v6 cand has a single row contract; historical tracking is not performed here.
            candidate = await engine.cand(row)
            model = candidate.get("model", {})
            probabilities = _ft_probabilities(model)
            if not all(k in probabilities for k in ("1", "X", "2")):
                skipped += 1
                continue
            ft_score = score_prediction(probabilities, actual)
            item = {"match_id": fixture.get("id"), "kickoff_ts": fixture.get("kickoff_ts"), "teams": row.get("Teams"), "actual_result": actual, "predicted_result": ft_score["predicted"], "probabilities": probabilities, "match_result_score": ft_score}
            goal_probs = _ou_probabilities(model)
            actual_goals = _actual_goals(fixture)
            if actual_goals and goal_probs:
                gs = _score_multiclass(goal_probs, actual_goals, ("over_2_5", "under_2_5"))
                item["goals_score"] = gs; metrics["goals"].append(gs)
            btts_probs = _btts_probabilities(model)
            actual_btts = _actual_btts(fixture)
            if actual_btts and btts_probs:
                bs = _score_multiclass(btts_probs, "btts_yes" if actual_btts == "yes" else "btts_no", ("btts_yes", "btts_no"))
                item["btts_score"] = bs; metrics["btts"].append(bs)
            actual_htft = _actual_htft(fixture)
            iyms = ((model.get("iyms") or {}).get("probabilities") or {})
            keys = ("1/1", "1/X", "1/2", "X/1", "X/X", "X/2", "2/1", "2/X", "2/2")
            if actual_htft and all(k in iyms for k in keys):
                hs = _score_multiclass(iyms, actual_htft, keys)
                item["htft_score"] = hs; metrics["htft"].append(hs)
            rows.append(item); metrics["match_result"].append(ft_score)
        except Exception as exc:
            skipped += 1
            rows.append({"match_id": fixture.get("id"), "error": str(exc)[:300]})

    def summarize(items: list[dict[str, Any]]) -> dict[str, Any] | None:
        if not items: return None
        return {"sample": len(items), "accuracy_pct": round(sum(x["correct"] for x in items) / len(items) * 100, 2), "brier_score": round(sum(x["brier"] for x in items) / len(items), 6)}

    ft = summarize(metrics["match_result"])
    if not ft:
        return {"available": True, "engine": engine.ENGINE, "engine_version": engine.VERSION, "sample": 0, "skipped": skipped, "message": "No completed fixtures could be scored.", "rows": rows}
    return {"available": True, "engine": engine.ENGINE, "engine_version": engine.VERSION, "sample": ft["sample"], "skipped": skipped, "accuracy_pct": ft["accuracy_pct"], "brier_score": ft["brier_score"], "metrics": {"match_result": ft, "goals_over_2_5": summarize(metrics["goals"]), "btts": summarize(metrics["btts"]), "htft": summarize(metrics["htft"])}, "rows": rows, "warning": "Backtest is a measurement, not a guarantee. Accuracy is valid only for the returned historical sample and production model version."}


async def run_historical_backtest(league_id: int, *, season: str | None = None, start_time: int | None = None, end_time: int | None = None, limit: int = 100) -> dict[str, Any]:
    fixtures = await fetch_historical_fixtures(league_id, season=season, start_time=start_time, end_time=end_time, limit=limit)
    result = await backtest_fixtures(fixtures)
    result["source"] = "5DollarFootballAPI /leagues/{id}/fixtures"
    result["requested"] = {"league_id": league_id, "season": season, "start_time": start_time, "end_time": end_time, "limit": limit}
    return result
