"""
Daily Picks Service -- the real backend behind "İdeal 4'lü" / "Sürpriz 4'lü" /
"İY/MS Sürpriz 4'lü". Replaces what used to be three free-text prompts sent
to the general chat endpoint (see bay-tahmin-pro's PredictionHub.tsx) with
one deterministic pipeline:

  1. Pull today's (or a requested date's) real, not-yet-started fixtures.
  2. Run the existing Prediction Engine on each candidate (capped, same
     rate-limit protection pattern already used by the chat orchestrator's
     `_daily_surprises` / `_reliable_matches`).
  3. Turn each analyzed fixture into zero or more `PickCandidate`s via
     `multi_market_engine` (ideal / surprise) or the existing İY/MS
     `surprise_engine` output already attached to the prediction.
  4. Rank and select exactly `limit` picks from DISTINCT matches.

Every number in the result traces back to a real fixture and a real model
output -- nothing here is generated by an LLM.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime, timezone
from zoneinfo import ZoneInfo

from app.core.exceptions import BayTahminError
from app.intelligence import multi_market_engine as mme
from app.providers.models import Fixture, MatchRawDataset
from app.schemas.picks import DailyPicksResponse, PickCandidate
from app.schemas.prediction import MatchPrediction
from app.services.analysis_service import AnalysisService
from app.services.fixture_selection import select_upcoming

ISTANBUL = ZoneInfo("Europe/Istanbul")

# Analyzing a fixture means several outbound calls to the data provider
# (team history, H2H, odds). An unfiltered day can have hundreds of
# fixtures across dozens of leagues; walking all of them risks hitting the
# provider's rate limit and returning nothing. This mirrors the same cap
# already used by `ChatOrchestrator._daily_surprises`.
MAX_CANDIDATES = 40

_DISCLAIMERS = {
    "ideal": (
        "[İdeal 4'lü] Bu 4 seçim, günün gerçek açık marketli maçları arasından, modelin "
        "farklı pazarlar (Maç Sonucu, Çifte Şans, Alt/Üst, Karşılıklı Gol) içinde en yüksek "
        "olasılıkla desteklediği seçenekler karşılaştırılarak oluşturuldu. Düşük risk hedefler, "
        "ama garanti/banko anlamına gelmez."
    ),
    "surprise": (
        "[Sürpriz 4'lü] Bu 4 seçim, İY/MS HARİÇ gerçek bahis pazarlarında (Maç Sonucu, Alt/Üst, "
        "Karşılıklı Gol, Asya Handikap) modelin piyasadan belirgin şekilde ayrıştığı, düz "
        "favorileri İÇERMEYEN seçeneklerden oluşturuldu. Yüksek risk/yüksek getiri potansiyeli "
        "taşır, kesin sonuç değildir."
    ),
    "iyms_surprise": (
        "[İY/MS Sürpriz 4'lü] Bu 4 seçim, günün maçlarında İlk Yarı/Maç Sonucu kombinasyonlarının "
        "(1/1, X/X, 2/2 rutin kombinasyonları hariç tutularak) modelin piyasayla ayrıştığı en güçlü "
        "adaylarından, mümkün olduğunca farklı maç ve farklı kombinasyonlar seçilerek oluşturuldu."
    ),
}


@dataclass
class _Analyzed:
    fixture: Fixture
    prediction: MatchPrediction
    dataset: MatchRawDataset


class DailyPicksService:
    def __init__(self, analysis_service: AnalysisService):
        self._service = analysis_service

    async def _future_fixtures(self, target: date) -> list[Fixture]:
        fixtures = await self._service._provider.get_fixtures(target)
        return select_upcoming(fixtures, target_date=target)[:MAX_CANDIDATES]

    async def _analyze_all(self, fixtures: list[Fixture]) -> list[_Analyzed]:
        out: list[_Analyzed] = []
        for fixture in fixtures:
            try:
                prediction = await self._service.analyze_match(fixture.match_id)
                dataset = await self._service.get_dataset(fixture.match_id)
            except BayTahminError:
                continue
            out.append(_Analyzed(fixture=fixture, prediction=prediction, dataset=dataset))
        return out

    async def build(self, category: str, target: date, limit: int = 4) -> DailyPicksResponse:
        if category not in _DISCLAIMERS:
            raise ValueError(f"Unknown picks category: {category!r}")

        fixtures = await self._future_fixtures(target)
        analyzed = await self._analyze_all(fixtures)

        if category == "ideal":
            picks = self._build_ideal(analyzed, limit)
        elif category == "surprise":
            picks = self._build_surprise(analyzed, limit)
        else:
            picks = self._build_iyms_surprise(analyzed, limit)

        note = None
        if not picks:
            note = (
                f"{target.isoformat()} için piyasası açık ve bu kategorinin kriterlerini "
                "karşılayan yeterli gerçek maç bulunamadı."
            )
        elif len(picks) < limit:
            note = f"Bu kriterleri karşılayan yalnızca {len(picks)} gerçek maç bulundu."

        return DailyPicksResponse(
            generated_at=datetime.now(timezone.utc), target_date=target, category=category,
            picks=picks, candidates_considered=len(analyzed),
            disclaimer=_DISCLAIMERS[category], note=note,
        )

    @staticmethod
    def _build_ideal(analyzed: list[_Analyzed], limit: int) -> list[PickCandidate]:
        scored: list[PickCandidate] = []
        for item in analyzed:
            candidate = mme.ideal_candidate_for_match(item.prediction, item.dataset)
            if candidate is not None:
                scored.append(candidate)
        scored.sort(key=lambda c: (c.model_probability, c.confidence), reverse=True)
        return scored[:limit]

    @staticmethod
    def _build_surprise(analyzed: list[_Analyzed], limit: int) -> list[PickCandidate]:
        pool: list[PickCandidate] = []
        for item in analyzed:
            pool.extend(mme.surprise_candidates_for_match(item.prediction, item.dataset))
        pool.sort(key=lambda c: c.divergence or 0.0, reverse=True)

        chosen: list[PickCandidate] = []
        seen_matches: set[str] = set()
        for candidate in pool:
            if candidate.match_id in seen_matches:
                continue
            chosen.append(candidate)
            seen_matches.add(candidate.match_id)
            if len(chosen) >= limit:
                break
        return chosen

    @staticmethod
    def _build_iyms_surprise(analyzed: list[_Analyzed], limit: int) -> list[PickCandidate]:
        pool = [
            (surprise.confidence, item, surprise)
            for item in analyzed
            for surprise in item.prediction.surprises
        ]
        pool.sort(key=lambda row: row[0], reverse=True)

        def to_pick(item: _Analyzed, surprise) -> PickCandidate:
            fixture, prediction = item.fixture, item.prediction
            return PickCandidate(
                match_id=fixture.match_id, home_team=prediction.home_team.team_name,
                away_team=prediction.away_team.team_name, league_name=fixture.league_name,
                kickoff=fixture.kickoff, market="İlk Yarı/Maç Sonucu (İY/MS)", selection=surprise.combination,
                model_probability=surprise.plausibility, market_probability=None, divergence=None,
                confidence=surprise.confidence, risk=surprise.risk, data_quality=prediction.data_quality,
                rationale=surprise.description,
            )

        chosen: list[PickCandidate] = []
        seen_matches: set[str] = set()
        seen_combos: set[str] = set()

        # Pass 1: prefer both a new match AND a new İY/MS combination, so
        # the 4 picks are genuinely varied rather than "X/1 four times over".
        for _score, item, surprise in pool:
            if len(chosen) >= limit:
                break
            if item.fixture.match_id in seen_matches or surprise.combination in seen_combos:
                continue
            chosen.append(to_pick(item, surprise))
            seen_matches.add(item.fixture.match_id)
            seen_combos.add(surprise.combination)

        # Pass 2: still one pick per match, but combos may repeat if there
        # weren't enough distinct combinations across distinct matches.
        if len(chosen) < limit:
            for _score, item, surprise in pool:
                if len(chosen) >= limit:
                    break
                if item.fixture.match_id in seen_matches:
                    continue
                chosen.append(to_pick(item, surprise))
                seen_matches.add(item.fixture.match_id)

        return chosen[:limit]
