"""
Daily Picks schemas (spec: "İdeal 4'lü" / "Sürpriz 4'lü" / "İY/MS Sürpriz 4'lü").

These three "quartet" products need a single, consistent shape: N concrete,
distinct real fixtures, each with one concrete market+selection, backed by
real model numbers -- never free-text generated by a chat model. See
`app/services/daily_picks_service.py` for how candidates are built and
ranked; this module only defines the response contract.
"""
from __future__ import annotations

from datetime import date, datetime
from typing import Optional

from pydantic import BaseModel

from app.schemas.common import DataQuality, RiskLevel


class PickCandidate(BaseModel):
    match_id: str
    home_team: str
    away_team: str
    league_name: Optional[str] = None
    kickoff: datetime

    # e.g. "Maç Sonucu (1X2)", "Alt/Üst 2.5", "Karşılıklı Gol (KG)",
    # "Asya Handikap -0.5", "İlk Yarı/Maç Sonucu (İY/MS)"
    market: str
    # e.g. "Galatasaray", "Üst 2.5", "Var", "X/1"
    selection: str

    model_probability: float
    market_probability: Optional[float] = None
    # model_probability - market_probability, when a market exists for this
    # exact selection. Positive = model more confident than the market.
    divergence: Optional[float] = None

    confidence: float
    risk: RiskLevel
    data_quality: DataQuality
    rationale: str


class DailyPicksResponse(BaseModel):
    generated_at: datetime
    target_date: date
    category: str  # "ideal" | "surprise" | "iyms_surprise"
    picks: list[PickCandidate]
    candidates_considered: int
    disclaimer: str
    note: Optional[str] = None
